### ISSUE TITLE
unnecessary python 3.9 limitation 

### ISSUE THREAD

**Issue by Heatdh** [AlexanderLutsenko/nobuco#18]
Hi,
the str.removesuffix comes with python 3.9 and add unecessary version constraint. 
Please consider switching: 
__all__ = [basename(f).removesuffix('.py') for f in modules if isfile(f) and not f.endswith('__init__.py')]
to: 
__all__ = [basename(f)[:-3] if f.endswith('.py') else basename(f) for f in modules if isfile(f) and not f.endswith('__init__.py')]

In addition the library is not intuitevly compatible with all torch versions (linalg comes starting > 1.17 and _six is depreceated for newer torch versions). it would be great if the user get an explicit requirements txt and add an instruction to installing the library as  developper mode (-e . ).
Best regards
Rayen

**Comment by AlexanderLutsenko** [comment]
> the str.removesuffix comes with python 3.9 and add unecessary version constraint

Good find, thanks!

> it would be great if the user get an explicit requirements txt

Done.

As for editable install, it's the standard procedure:

```console
git clone https://github.com/AlexanderLutsenko/nobuco.git
pip install -e ./nobuco
```
