### ISSUE TITLE
Custom Softplus Layer and Einsum Error when load_model with Keras

### ISSUE THREAD

**Issue by wredan** [AlexanderLutsenko/nobuco#23]
Hi! Thanks so much for the amazing conversion tool! The readme doc is so well written 🎉

I am not an expert at all in Keras/Tensorflow, but I'm trying to convert a model from pytorch to tf that is using a softplus activation. I've read in tf docs that there is a slightly different implementation from the pytorch one, but I want to give it a try anyway. So I implemented a converter as you suggest:

```py
@nobuco.converter(F.softplus, channel_ordering_strategy=ChannelOrderingStrategy.MINIMUM_TRANSPOSITIONS)
def converter_softplus(input):
    def func(input):
        return tf.keras.activations.softplus(input)
    return func
```
with this custom converter, `pytorch_to_keras(...)` goes straight green on the whole model. Then I save the model with `keras_model.save(f'{export_name}.h5')`.

So far so good!

Now I want to test the model by making an inference, so I use the following code:

```py
# prompt
dummy_prompt_keras = "Harry Potter"
input_ids_keras = tokenizer(dummy_prompt_keras, return_tensors='tf').input_ids

# loading model
keras_model = tf.keras.models.load_model(f'{export_name}.h5')
#keras_model.summary()

# inference
out = keras_model.predict(input_ids_keras)

# output
print(out)
```
but I get an error on the line: 

```py
keras_model = tf.keras.models.load_model(f'{export_name}.h5')
```
the error stacktrace is:

```console
"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
...
...
File ~/miniconda3/envs/deepl/lib/python3.11/site-packages/nobuco/node_converters/linear.py:102, in converter_einsum.<locals>.func.<locals>.<lambda>(operands)
    100 equation = args[0]
    101 operands = args[1:]
--> 102 return keras.layers.Lambda(lambda operands: tf.einsum(equation, *operands))(operands)

AttributeError: Exception encountered when calling layer \"lambda_12\" (type Lambda).

'list' object has no attribute 'shape'

Call arguments received by layer \"lambda_12\" (type Lambda):
  • inputs=['tf.Tensor(shape=(None, None, 10), dtype=float32)', [['tf.Tensor(shape=(), dtype=float32)', 'tf.Tensor(shape=(), dtype=float32)', 'tf.Tensor(shape=(), dtype=float32)', 'tf.Tensor(shape=(), dtype=float32)', 'tf.Tensor(shape=(), dtype=float32)', 'tf.Tensor(shape=(), dtype=float32)', ... ]]]
  • mask=None
  • training=None"
}
```
`lambda_12` layer relates to an einsum operation by einops, which uses a torch.einsum under the hood I guess. I also tested with native torch.einsum but same error. So, my custom softplus layer is supposed to output a Tensor, which is then picked up by the einsum layer. However, this does not seem to be the case, as indicated by the stacktrace.

I'm using the following code for conversion:
```py
keras_model = nobuco.pytorch_to_keras(
    model,
    args=[input_ids], kwargs=None,
    input_shapes={input_ids: (None, None)},
    inputs_channel_order=ChannelOrder.TENSORFLOW,
    outputs_channel_order=ChannelOrder.TENSORFLOW,
    constants_to_variables=False,
    trace_shape=True,
)
```

This is the libs version I'm using:
```
nobuco                       0.11.5
keras                        2.15.0
torch                        2.2.0+cu118
tensorflow                   2.15.0.post1
```
Do you have any idea or any tips to get along with this error? I'm sure there is some dumb mistake I made, but I'm struggling to spot it. If you could help It would be very much appreciated.

Thanks again for the amazing work on this project!

**Comment by AlexanderLutsenko** [comment]
Hi! I'm struggling to reproduce the problem, can you help me with that? A minimal (not)working example would be much appreciated, or at least the debug output (`trace.html` which is produced when `save_trace_html=True` ).

As a possible quick fix, try to save the keras model in `SavedModel` format:
```python
export_path = `model_path/model_dir`  # No '.h5' in the path!
keras_model.save(export_path)
keras_model_restored = tf.saved_model.load(export_path)
```

**Comment by wredan** [comment]
Hi, thanks for the reply!

[Here ](https://github.com/wredan/mamba-minimal/blob/keras/to-keras.ipynb) you can find some code examples. I left the cell outputs I got.

I've done some digging actually, and the issue is not about nobuco (which is great so far!), but with the serialization when saving the model. Exporting and importing it as `SavedModel ` works well as you can see in the notebook. I found an issue where in your last part of [this](https://github.com/AlexanderLutsenko/nobuco/issues/22#issuecomment-1930251236) reply you mention about some bugs with keras 2.*, this is the case I guess. 

I even tried to create multiple conda env where in the first one I installed nobuco compatible tensorflow/keras (2.15.0, the last one published till now) and exported my models. In the second one, I installed the nightly version which should use keras 3, but here I could not use nobuco nor import a model saved with the 2.15 version of tensorflow due to imports refactoring or missing classes.

My issue is that I actually need a serialized `.keras` or `.h5` file and not a `SavedModel ` because I need the file to be parsed by another tool that accepts only .keras/.h5 model files.

I'm really sorry to bother you if Nobuco is not the problem, but if you have any hints or could help deal with this serialization issue, or suggest some other repo to post an issue, I would be so grateful.

Thanks again!

**Comment by AlexanderLutsenko** [comment]
Hm, interesting. The problem only manifests itself with `constants_to_variables=False` parameter.

**Comment by AlexanderLutsenko** [comment]
> unfortunately I cannot pass a custom_objects to that tool

Whatever that tool is, can you invoke it inside your script? If so, [custom_object_scope](https://www.tensorflow.org/api_docs/python/tf/keras/saving/custom_object_scope) might help:

```python
from keras.src.saving.object_registration import custom_object_scope

custom_objects = {'WeightLayer': WeightLayer}
with custom_object_scope(custom_objects):
    keras_model_restored = keras.models.load_model(model_path + '.h5')
```

**Comment by AlexanderLutsenko** [comment]
I don't think you can get away without `custom_objects`. There's a loop inside `selective_scan` which won't be traced automatically. Due to the current limitations of Keras, the only way to add it into the graph is to create a custom layer (or at least I have not found another way). See [Mamba example](https://github.com/AlexanderLutsenko/nobuco/tree/master/examples/mamba_minimal) for details.

**Comment by wredan** [comment]
Yes, I haven’t found any other way eather. I think I'm going to stick with `custom_object` in some way or keep looking for alternative to tf or tflite, like playing with onnx.

Thank you so much for the support and the example integrated in the nobuco repo.

I'm going to close this issue for now because it is not an actual nobuco problem.

Thanks again.
