### ISSUE TITLE
raise Exception(f'Failed conversion: {self.original_node}')

### ISSUE THREAD

**Issue by mr-sarthakgupta** [AlexanderLutsenko/nobuco#28]
Getting the following error while trying to convert my model, have all the dependencies installed according to the requirements.txt provided in the repo

<img width="631" alt="issue" src="https://github.com/AlexanderLutsenko/nobuco/assets/81774392/adf26380-2dde-4ebc-a28f-dee4ab306b18">

**Comment by AlexanderLutsenko** [comment]
Hi! Could you run the conversion with `save_trace_html=True` and show me the `trace.html` file?

**Comment by AlexanderLutsenko** [comment]
Closing the issue for now due to inactivity. Please reopen if it's still relevant.
