### ISSUE TITLE
When groups equal input channels then PyTorch Conv2D is mapped to Keras DepthwiseConv2D

### ISSUE THREAD

**Issue by dr-costas** [AlexanderLutsenko/nobuco#33]
Hi!

First of all, thank you so much for this work! Hats off :) 

Then, I noticed that at the `nobuco/node_converters/convolution.py` there is the: 

```python
is_depthwise = groups == in_filters
```

which then is used to select the `keras.layers.DepthwiseConvXD` version of the ConvXD layers in Keras. Though, this creates problems when the stride is not same in height and width. For example, in PyTorch one can do: 

```python
import torch
torch.nn.Conv2D(
    in_channels=4,
    out_channels=4,
    kernel_size=(1, 3),
    stride=(1, 2),
    groups=4,
)
```

but the above, and because of the `is_depthwise = groups == in_filters`, will be translated to

```python
import keras, numpy as np
x = np.random.rand(4, 10, 10, 12)
keras.layers.DepthwiseConv2D(
    (1, 3),
    strides=(1, 2),
)(x)
```

Which then will give:

```
InvalidArgumentError: Exception encountered when calling layer 'depthwise_conv2d_1' (type DepthwiseConv2D).

{{function_node __wrapped__DepthwiseConv2dNative_device_/job:localhost/replica:0/task:0/device:CPU:0}} Current implementation only supports equal length strides in the row and column dimensions. [Op:DepthwiseConv2dNative] name: 

Call arguments received by layer 'depthwise_conv2d_1' (type DepthwiseConv2D):
  • inputs=tf.Tensor(shape=(4, 10, 10, 12), dtype=float32)
```

But, if typical Conv2D is used instead of DepthwiseConv2D, like:

```python
import keras, numpy as np
x = np.random.rand(4, 10, 10, 12)
keras.layers.Conv2D(
    (1, 3),
    strides=(1, 2),
    groups=12
)(x)
```

then it will work. 

I have quit using keras since before Theano was deprecated (was that 2017?) and I'm not familiar what is the actual difference between `keras.layers.DepthwiseConv2D` and `keras.layers.Conv2D`. But if it is just about the setting of the groups, then maybe either add one more checking (e.g. `is_stride_ok = all([stride[0] == x for x in stride])`) or maybe not use `keras.layers.DepthwiseConv`?

Any insights? 

Thank you!

**Comment by AlexanderLutsenko** [comment]
Hi! Funnily enough, that was brought in by a recent fix: https://github.com/AlexanderLutsenko/nobuco/issues/30

It's unclear how to get convolution working in as many cases as possible with minimal tinkering. Need to mull it over.

**Comment by dr-costas** [comment]
I read the issue and I understand the problem and the different options. Maybe adding one flag at the `nobuco.pytorch_to_keras` method, something like

```python
dummy_image = torch.rand(size=(1, 3, 256, 256))
pytorch_module = MyModule().eval()

keras_model = nobuco.pytorch_to_keras(
    pytorch_module,
    args=[dummy_image], kwargs=None,
    inputs_channel_order=ChannelOrder.TENSORFLOW,
    outputs_channel_order=ChannelOrder.TENSORFLOW,
    prefer_depthwise=False,
)
```

Or? I can understand that you (most probably) have some design considerations already in-place for nobuco, so the above might be totally out of these considerations :D 

But it would be nice to have the option to choose between using the depthwise implementation of Keras/TF over a regular grouped ConvXD, that can result in the issue mentioned by #30

**Comment by AlexanderLutsenko** [comment]
> is_stride_ok = all([stride[0] == x for x in stride])

Seems like this approach is the best one, pushed a fix in `v0.13.3`.

**Comment by dr-costas** [comment]
Or even the following can be done at `nobuco/node_converters/convolution.py `:

```python
is_depthwise = groups == in_filters and is_stride_ok = all([stride[0] == x for x in stride])
```

**Comment by dr-costas** [comment]
😆 

I just wrote the above!

Amazing! Thank you so much for this.
