### ISSUE TITLE
TypeError: converter_mean() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by hengck23** [AlexanderLutsenko/nobuco#4]
This code has error

x = x.mean(0,keepdims=True)

```
  File "/home/titanx/hengck/opt/anaconda3.9/lib/python3.9/site-packages/nobuco/converters/node_converter.py", line 48, in decorator
    converter_result_func = converter_func(*args, **kwargs)
TypeError: converter_mean() got an unexpected keyword argument 'keepdims'
```

But i can get rid of it using:
x = x.mean(0).unsqueeze(0)

**Comment by AlexanderLutsenko** [comment]
That's weird... The [parameter's name is `keepdim`](https://pytorch.org/docs/stable/generated/torch.mean.html), but `keepdims` also works somehow. Anyways, below is the solution to your problem:

```python
x = x.mean(0,keepdim=True)
```

**Comment by hengck23** [comment]
it works. thanks!
