### ISSUE TITLE
Signature output names

### ISSUE THREAD

**Issue by johan-sightic** [AlexanderLutsenko/nobuco#51]
I have a pytorch model that returns a `dict[str, torch.Tensor]` type with 5 keys and tensors and I use nobuco to convert it to tflite.
Conversion works fine, however, the output of the tflite model is now a dict with different keys. The signature of the tflite model is:
```
Signature#0 key: 'serving_default'
- Subgraph: Subgraph#0
- Inputs: 
    'args_0' : T#0
- Outputs: 
    'tf.identity' : T#206
    'tf.identity_1' : T#208
    'tf.identity_2' : T#210
    'tf.identity_3' : T#212
    'tf.identity_4' : T#214
```
How can I change the output keys to match my original model?
Thanks!

**Comment by AlexanderLutsenko** [comment]
Hi! Signatures are supported since `v0.15.0`, see [example](https://github.com/AlexanderLutsenko/nobuco/blob/55612ec5e5daf77fc7b34c94fabfad5c7340c326/examples/signature.py). Note: you'll have to use `TFLiteConverterV2`, not the old `TFLiteConverter`.

**Comment by johan-sightic** [comment]
Perfect, thank you!
