### ISSUE TITLE
Thank you for releasing this wonderful repository.

### ISSUE THREAD

**Issue by PINTO0309** [AlexanderLutsenko/nobuco#6]
Thanks for your very clear insight and support on my repository [issue](https://github.com/PINTO0309/onnx2tf/issues/327). :smile: 

I just wanted to post this issue to say thanks. Sorry if this is a nuisance to you.
The purpose of the repository (onnx2tf) I was creating was to generate TensorFlow models from PyTorch, but your tool is much more complete. The source code is very clean and I am very impressed.

So, I have a question: I will of course consider issuing a pull request to this repository someday, but may I use your clean source code as a reference and quote your implementation to my repository? Since the overall design of the tools is very different, it is not possible to quote them in exactly the same way, but clean OP as conversion patterns are very helpful. For example, implementations of `While-Loop` and `GridSample`.

However, I would like to contribute to this repository someday, as I cannot rely on you all the time.
I am sorry for taking up so much of your valuable time.
Again, thanks.

**Comment by PINTO0309** [comment]
Thank you for your warm words.

One day I will contribute to this tool.

**Comment by juanwil87** [comment]
This is a wonderful repository!!! This repo should become part of Tensorflow 👍
