### ISSUE TITLE
Extremely High GPU VRAM Usage During Conversion

### ISSUE THREAD

**Issue by chadrockey** [AlexanderLutsenko/nobuco#61]
I've observed an issue where occasionally my VM sessions will crash and I tracked it down to VRAM usage during the conversion.

Here is a typical amount of VRAM usage:
<img width="342" alt="Screenshot 2024-08-01 at 12 25 03 AM" src="https://github.com/user-attachments/assets/abd08a8b-0574-4fbb-805c-0677b3b4331c">

And here is the jump when the conversion begins:
<img width="341" alt="Screenshot 2024-08-01 at 12 28 53 AM" src="https://github.com/user-attachments/assets/942d14dd-82a5-40f9-ad17-1cd6ed649aec">

I was able to avoid this by adding this before the conversion.  Then the VRAM isn't increased and even the normal ram isn't increased at all.

```
    import tensorflow as tf
    tf.config.experimental.set_visible_devices([], 'GPU')
```

**Comment by AlexanderLutsenko** [comment]
Hi! That one seems to be a problem with Tensorflow itself. During conversion, it's usually a good idea to disable the GPU altogether:

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = ""
```

**Comment by chadrockey** [comment]
Ah thanks, I haven't seen this since I implemented the fix in my comment.  I am converting at the end of a PyTorch training notebook, so I can't disable cuda entirely, but can hide it from tensorflow.

I was doing the conversions in a separate notebook / after the fact, but PyTorch doesn't save the full model structure in the exported files as best I can tell.  You still need the model class available to convert.  Are you aware of any way to save a fully portable PyTorch model?
