### ISSUE TITLE
Quantization support?

### ISSUE THREAD

**Issue by happyTonakai** [AlexanderLutsenko/nobuco#68]
Hi! I use nobuco to convert pytorch model to keras and then to tflite for edge device and it works fine. Thank you for the great work.

I'm wondering if nobuco supports quantization model, both post training quantization and quantization aware training?

**Comment by AlexanderLutsenko** [comment]
Hi! Post-training quantization can be performed on the converted Keras model, although I've seen reports that it does a much worse job than Pytorch.
Converting an already quantized model is possible in theory. In practice, I don't see the needed quantized operations in Tensorflow. Feel free to join the related discussion: https://github.com/AlexanderLutsenko/nobuco/discussions/40.

**Comment by happyTonakai** [comment]
Oh, I didn't see that discussion. I'll have a look and close this issue. Thank you!
