### ISSUE TITLE
pytorch version?

### ISSUE THREAD

**Issue by mychina75** [AlexanderLutsenko/nobuco#8]
Thanks for your work.
When try to run dynamic_shape.py, I got error info like following:
AttributeError: module 'torch.nn.functional' has no attribute '_canonical_mask'
AttributeError: module 'torch' has no attribute 'fill'
etc...

I think may caused by pytorch version. which version are you using?

**Comment by AlexanderLutsenko** [comment]
@mychina75 Hi! As you can see [here](https://github.com/AlexanderLutsenko/nobuco#installation-), it's Pytorch 2.0.0 (or newer). I should probably add guards against such type of errors. You only need v2.x.x for that `F._canonical_mask` function. Thank's for bringing this up.
